### ISSUE TITLE
[Suggestion] Add JS FPS

### ISSUE THREAD

**Issue by gentlee** [bamlab/flashlight#175]
From device debug menu you can open perf monitor with both native FPS and JS FPS.

Native FPS for RN app is not very usefull as the main thread in most times is not doing much work, while JS thread is often doing a lot of work and cause app unresponsiveness.

Would be nice to have that parameter in this plugin, and use it also for performance score.

**Comment by Almouro** [comment]
Hi @gentlee, 

There's a guide here https://docs.flashlight.dev/guides/react-native/js-fps on how to correlate JS FPS with the stats given by Flashlight.
Let me know if that's clear!

It might be useful though to make the JS thread usage more prominent for React Native apps, so that's an idea I'll think about 🤔

**Comment by Almouro** [comment]
We now make it clearer that we're showing the RN JS thread, closing this issue then!

<img width="603" alt="image" src="https://github.com/bamlab/flashlight/assets/4534323/e2527984-e13b-478b-a38d-59d0a666f8cc">
