### ISSUE TITLE
Q: What does "Process id has changed" error mean?

### ISSUE THREAD

**Issue by Nodonisko** [bamlab/flashlight#180]
Hi, I sometimes getting this error:

![Screenshot 2023-12-08 at 16 24 19](https://github.com/bamlab/flashlight/assets/5837757/93e13c3d-94f4-47f7-af13-fc7dd0d8a8a5)

I tried restart app, restart flashlight but it did not help and then it suddently start to work and work for a while and then again this error.

What does this error mean?

Thanks.

**Comment by Almouro** [comment]
Hi @Nodonisko!

It's supposed to mean that Flashlight detected that the app has a different process id than before. This usually happens if the app is restarted (or has crashed) for instance

(Technically it happens when Flashlight doesn't find a file for the app process https://github.com/bamlab/flashlight/blob/main/packages/platforms/android/cpp-profiler/src/main.cpp#L49)

But it's quite weird that it happens so often 🤔
Does it happen for every app or just this one?

**Comment by KamakshiOjha** [comment]
The 'Process id has changed' error indicates a disruption in the tracking process of the Lighthouse for Mobile app. This error commonly occurs when there is a sudden change or interruption in the application's execution environment, leading to a mismatch in process identification. To address this, first, analyze the error message context and check the project documentation for any specific information about this error. Investigate the codebase for potential causes, considering recent changes or updates that might have triggered the issue.

**Comment by Nodonisko** [comment]
Thanks for explanation @Almouro I did tried Flashlight only with this one app. I will close issue now and reopen it if I encounter it again.
