### ISSUE TITLE
unable to measure anything on Windows

### ISSUE THREAD

**Issue by mark-zacharias** [bamlab/flashlight#76]
When I try to click auto detect the flipper plugin crashes.
![image](https://user-images.githubusercontent.com/5340574/224445989-b04a334b-6f6c-4101-8e27-263b6d1343f0.png)
If I type in the box it throws up an error after each character.  I was able to put a bundle id in by pasting the full id into the box.
However, the plugin then crashes when I click start measuring.
![image](https://user-images.githubusercontent.com/5340574/224447329-136f5a8b-b2b4-4223-a5d2-b27a18e95bc1.png)

Is there a configuration option I'm missing?  Not sure what the issue might be.

**Comment by Almouro** [comment]
Hi @mark-zacharias, thanks for raising an issue here!
As it turns out, Flashlight needs a few fixes to make it work with Windows properly 🙈. 

I've started with a few fixes, see #77 to see the ongoing work! 🚧

I haven't tried it, but I'm guessing Flashlight works with [WSL](https://learn.microsoft.com/en-us/windows/wsl/install), however I think the fixes should be simple enough to make it work with native Windows.

**Comment by mark-zacharias** [comment]
Aha, that makes sense. I'll try and pull that code down and give it a test.
